# building from Alpine Linux
FROM alpine:3.12

# update the apk package manager and install nginx, openssl and openssh
RUN apk update && apk upgrade && \
	apk add nginx && \
	apk add openssl && \
	apk add openssh 

# creating a folder for nginx.pid and for www
RUN mkdir /var/run/nginx && mkdir /www

# adding user www for nginx
RUN adduser -D -g 'www' www

RUN chown -R root:root /etc/ssl && \
	chmod -R 600 /etc/ssl

# changing the user ID for the hierarchies rooted in the files
RUN chown -R www:www /var/lib/nginx && \
	chown -R www:www /www

# creating new key and ssl certificate and putting them in the right directory
RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -subj '/C=NL/ST=Noord-Holland/O=Codam/CN=kubernetes' -keyout /etc/ssl/nginx.key -out /etc/ssl/nginx.crt

# copying the nginx configuration file and the index page to the container
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /www/index.html 
# COPY supervisor.conf /etc/ssl/supervisor.conf
COPY sshd_config /etc/ssh/sshd_config

# adding a user for the ssh and changing the password everywhere
run adduser -h / -D mmourik && \
	echo "mmourik:strawberry" | chpasswd		

# copy the startup.sh to the container
COPY start.sh /start.sh

# give the correct execution rights to the start.sh
RUN chmod +x ./start.sh

# expose the correct ports
EXPOSE 22 80 443

# give the command to start the container
CMD ./start.sh