apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      serviceAccount: mmourik
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp-data
        - containerPort: 21
          name: ftps
        - containerPort: 10003
          name: passive3
        - containerPort: 10004
          name: passive4
        - containerPort: 10005
          name: passive5

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-service
spec:
  ports:  
  - name: ftp-data
    port: 20
    protocol: TCP
    targetPort: 20 
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: passive3
    port: 10003
    protocol: TCP
    targetPort: 10003
  - name: passive4
    port: 10004
    protocol: TCP
    targetPort: 10004
  - name: passive5
    port: 10005
    protocol: TCP
    targetPort: 10005
  selector:
    app: ftps
  type: LoadBalancer
