apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: wordpress-secret
        ports:
        - containerPort: 5050
          name: http
       
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
    - name: http
      port: 5050
      protocol: TCP
      targetPort: 5050  
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
stringData:
  WP_TITLE: wordpress
  WP_USER: mmourik      
  WP_PASSWORD: strawberry
