apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      serviceAccount: mmourik
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp-data
        - containerPort: 21
          name: ftp-command
        - containerPort: 20001
          name: passive-one
        - containerPort: 20002
          name: passive-two
        - containerPort: 20003
          name: passive-three
        - containerPort: 20004
          name: passive-four
        - containerPort: 20005
          name: passive-five

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-service
spec:
  ports:
  - name: ftp-data
    port: 20
    protocol: TCP
    targetPort: 20
  - name: ftp-command
    port: 21
    protocol: TCP
    targetPort: 21
  - name: passive-one
    port: 20001
    protocol: TCP
    targetPort: 20001
  - name: passive-two
    port: 20002
    protocol: TCP
    targetPort: 20002    
  - name: passive-three
    port: 20003
    protocol: TCP
    targetPort: 20003
  - name: passive-four
    port: 20004
    protocol: TCP
    targetPort: 20004
  - name: passive-five
    port: 20005
    protocol: TCP
    targetPort: 20005
  selector:
    app: ftps
  type: LoadBalancer
