apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      serviceAccount: mmourik
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp-data
        - containerPort: 21
          name: ftp-control
        - containerPort: 10000
          name: passive-1
        - containerPort: 10001
          name: passive-2
        - containerPort: 10002
          name: passive-3

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: ftps-service
spec:
  ports:
  - name: ftp-data
    port: 20
    protocol: TCP
    targetPort: 20
  - name: ftp-control
    port: 21
    protocol: TCP
    targetPort: 21
  - name: passive-1
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: passive-2
    port: 10001
    protocol: TCP
    targetPort: 10001
  - name: passive-3
    port: 10002
    protocol: TCP
    targetPort: 10002
  selector:
    app: ftps
  type: LoadBalancer
